version: "3.8"

services:
    postgres:
        image: postgres:13
        ports:
            - ${POSTGRES_HOST:-127.0.0.1}:${POSTGRES_PORT:-5432}:5432
        environment:
            POSTGRES_PASSWORD: psql
        volumes:
            - pg_data:/var/lib/postgresql/data
            - ./postgres/init-server-db.sh:/docker-entrypoint-initdb.d/init-server-db.sh

    adminer:
        image: adminer:4
        ports:
            - ${ADMINER_HOST:-127.0.0.1}:${ADMINER_PORT:-15432}:8080
        links:
            - "postgres:db"

volumes:
    pg_data:
